name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    
    - name: Run tests
      run: mvn test
    
    - name: Build Docker image
      run: docker build -t otter:${{ github.sha }} .
    
    - name: Run security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'otter:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Push Docker image
      run: |
        docker tag otter:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/otter:${{ github.sha }}
        docker tag otter:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/otter:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/otter:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/otter:latest
    
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here 